config/routes.rb
Daveapp::Application.routes.draw do
  devise_for :users
  get 'lessons' => 'pages#lessons'
  get 'less1' => 'pages#less1'
  get 'less2' => 'pages#less2'

  root :to => 'pages#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<p class="pull-right"><a href="#">Back to top</a></p>
	<p>&copy; Bill Hurley, Inc.</p>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
                <div class="brand">
                    <%= link_to 'Dads Course',  root_path %>
                </div>
            
                    
					<ul class="nav pull-right">
                      <% if user_signed_in? %>
                        <li>    
                            <%= link_to 'Lessons',  lessons_path %>
                        </li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                            <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
					</ul>
					
			</div>
		</div>	
	</div>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dad's Course</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

 	<% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>

 	<div class="container">

		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

		
		
</body>
	
</html>

app/views/pages/about.html.erb
<h1>about</h1>

app/views/pages/home.html.erb
<h1 class="page-header">Welcome to Dad's New Course</h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/tgMFOu_4mfE" frameborder="0" allowfullscreen></iframe>

<h3>A place where students explore concepts before they enter the classroom.</h3>

<div class="well">
	<p>
	            <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>

	</p>
	<h3>Please take a look.</h3>
</div>

app/views/pages/less1.html.erb
<h1 class="page-header">Probability Tree - 2 Coins</h1> 

<iframe width="560" height="315" src="//www.youtube.com/embed/4vSbGpAF4Ts" frameborder="0" allowfullscreen></iframe>

<h2>Key Points</h2>
<div class="well">
	<ol>
		<li>Nemo enim ipsam voluptatem</li>
		<li>Sed ut perspiciatis unde omnis</li>
		<li>Nemo enim ipsam voluptatem quia </li>
	</ol>
</div>

<h2>Lecture Notes</h2>
<div class="well">
	<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

	<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
</div>
<h2>Exercises</h2>
<div class="well">
	<ol>
		<li>Nemo enim ipsam voluptatem</li>
		<li>Sed ut perspiciatis unde omnis</li>
		<li>Nemo enim ipsam voluptatem quia </li>
	</ol>
</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'dadcourse'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
   <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/pages/less2.html.erb
<h1 class="page-header">Summing the first N Integers</h1> 

<iframe width="560" height="315" src="//www.youtube.com/embed/m4R4cXNZIzI" frameborder="0" allowfullscreen></iframe>

<h2>Key Points</h2>
<div class="well">
	<ol>
		<li>Nemo enim ipsam voluptatem</li>
		<li>Sed ut perspiciatis unde omnis</li>
		<li>Nemo enim ipsam voluptatem quia </li>
	</ol>
</div>

<h2>Lecture Notes</h2>
<div class="well">
	<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

	<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
</div>
<h2>Exercises</h2>
<div class="well">
	<ol>
		<li>Nemo enim ipsam voluptatem</li>
		<li>Sed ut perspiciatis unde omnis</li>
		<li>Nemo enim ipsam voluptatem quia </li>
	</ol>
</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'dadcourse'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/pages/lessons.html.erb
<h1 class="page-header">Lessons</h1>

 <div class="container row-fluid">
        <div class="lesson span4 text-center">
          <h1>1</h1>
          <h4><%= link_to 'Probability Tree - 2 Coins', less1_path %></h4>

          <p>Calculating the probability of at least two Heads in two flips of an unbiased coin.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
          <h1>2</h1>
          <h4><%= link_to 'Summing the first N Integers', less2_path %></h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
         <h1>3</h1>
          <h4>Lesson 3</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
</div><!-- /.row -->
 <div class="container row-fluid">
        <div class="lesson span4 text-center">
          <h1>4</h1>
          <h4>Lesson 4</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
          <h1>5</h1>
          <h4>Lesson 5</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
         <h1>6</h1>
          <h4>Lesson 6</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
</div><!-- /.row -->
 <div class="container row-fluid">
        <div class="lesson span4 text-center">
          <h1>7</h1>
          <h4>Lesson 7</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
          <h1>8</h1>
          <h4>Lesson 8</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="lesson span4 text-center">
         <h1>9</h1>
          <h4>Lesson 9</h4>
          <p>Here you can write a quick desription of the lesson and what the student is expected to learn.</p>
          
        </div><!-- /.col-lg-4 -->
</div><!-- /.row -->